"""Initial revision english models

Revision ID: 46c286749b2c
Revises: 
Create Date: 2025-12-09 19:28:47.580686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c286749b2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('normal', 'admin')", name='chk_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('rides',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('address_from', sa.String(length=255), nullable=False),
    sa.Column('address_to', sa.String(length=255), nullable=False),
    sa.Column('departure', sa.TIMESTAMP(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'full', 'canceled', 'finished')", name='chk_ride_status'),
    sa.CheckConstraint('max_seats > 0', name='chk_trajet_places'),
    sa.CheckConstraint('price >= 0', name='chk_trajet_prix'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_index(op.f('ix_rides_ride_id'), 'rides', ['ride_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reservation_date', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'confirmed', 'canceled', 'finished')", name='chk_status_reservation'),
    sa.CheckConstraint('seats_booked > 0', name='chk_seats_booked'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.ride_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservations_reservation_id'), 'reservations', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_reservation_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_rides_ride_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
