"""Description de la migration

Revision ID: bb1e831c5cc2
Revises: 
Create Date: 2026-01-06 00:26:30.602756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1e831c5cc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('address_from', sa.String(length=255), nullable=False),
    sa.Column('address_to', sa.String(length=255), nullable=False),
    sa.Column('lat_from', sa.Float(), nullable=True),
    sa.Column('lng_from', sa.Float(), nullable=True),
    sa.Column('lat_to', sa.Float(), nullable=True),
    sa.Column('lng_to', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('from_iut', sa.Boolean(), nullable=False),
    sa.Column('departure', sa.TIMESTAMP(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'full', 'canceled', 'finished')", name='chk_ride_status'),
    sa.CheckConstraint('max_seats > 0', name='chk_trajet_places'),
    sa.CheckConstraint('price >= 0', name='chk_trajet_prix'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_index(op.f('ix_rides_ride_id'), 'rides', ['ride_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reservation_date', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'confirmed', 'canceled', 'finished')", name='chk_status_reservation'),
    sa.CheckConstraint('seats_booked > 0', name='chk_seats_booked'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.ride_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservations_reservation_id'), 'reservations', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_reservation_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_rides_ride_id'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###